# Generated by Django 5.2.12 on 2026-03-11 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='category',
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='icecream',
            name='wrapper',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.DeleteModel(
            name='IceCream',
        ),
        migrations.DeleteModel(
            name='Wrapper',
        ),
    ]
